# Generated by Django 3.2.16 on 2024-02-27 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusStopVehicleLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='locations')),
                ('but_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bv_stop', to='tracker.busstop')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bv_vehicle', to='tracker.vehicle')),
            ],
        ),
    ]
