# Generated by Django 3.2.16 on 2024-02-28 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_busstopvehiclelocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_id', models.IntegerField()),
                ('order', models.IntegerField()),
                ('distance', models.IntegerField()),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='path_location', to='tracker.location')),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='path',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_path', to='tracker.path'),
        ),
    ]
