# Generated by Django 3.2.16 on 2024-03-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20240228_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='path',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='path_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
