# Generated by Django 3.2.16 on 2024-03-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20240304_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='latitude',
            field=models.FloatField(default=38.573739),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='longitude',
            field=models.FloatField(default=68.78696),
            preserve_default=False,
        ),
    ]
