# Generated by Django 3.2.16 on 2024-03-04 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20240304_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclelocation',
            name='location',
        ),
        migrations.RemoveField(
            model_name='vehiclelocation',
            name='vehicle',
        ),
        migrations.DeleteModel(
            name='BusStopVehicleLocation',
        ),
        migrations.DeleteModel(
            name='VehicleLocation',
        ),
    ]
