# Generated by Django 3.2.16 on 2024-03-04 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20240304_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='longitude',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_location', to='tracker.location'),
        ),
    ]
