# Generated by Django 3.2.16 on 2024-03-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20240304_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='busstop',
            name='buses',
            field=models.ManyToManyField(to='tracker.Vehicle'),
        ),
    ]
